---
title: "Publications"
---

<style type="text/css">
h1.title {
  text-align: center;
}
</style>

<div align="center">
[Peer-reviewed]{style="color: teal; font-size: 15pt; font-weight: bold"}
</div>

#### 2022
**Maciejewski MF**, Bell AM. Insights into parental care from studies on non-mammalian vertebrates. Affect. Sci. 3: 792-798. [Link](https://link.springer.com/article/10.1007/s42761-022-00127-4)
\ 

Hund AK, Fuess LE, Kenney ML, **Maciejewski MF**, Marini JM, Shim KC, Bolnick DI. Population-level variation in parasite resistance due to differences in immune initiation and rate of response. Evol. Lett. 2: 162-177.
[Link](https://academic.oup.com/evlett/article/6/2/162/6697311)
\ 
\ 

#### 2020
**Maciejewski MF**, Jiang C, Stuart YE, Bolnick DI. Microhabitat contributes to microgeographic divergence in threespine stickleback. Evolution. 74: 749-763. [Link](https://onlinelibrary.wiley.com/doi/abs/10.1111/evo.13942)
\ 

#### 2019
**Maciejewski MF**, Hernandez CA, Bolnick DI. Investigating the association between armor coverage and parasite infection in an estuarine population of stickleback. Evol. Ecol. Res. 20: 69-82. [Link](http://www.evolutionary-ecology.com/issues/v20/n01/ffar3183.pdf)
\ 

**Maciejewski MF**, Meyer KS, Wheeler JD, Anderson EJ, Pittoors NC, Mullineaux LS. Helical swimming as an exploratory behavior in competent larvae of the eastern oyster (Crassostrea virginica). J. Exp. Mar. Biol. Ecol. 510: 86-94. [Link](https://www.sciencedirect.com/science/article/pii/S0022098118302879)
\ 

\ 

<div align="center">
[In prep]{style="color: teal; font-size: 15pt; font-weight: bold"}
</div>

Bell SE, Xie RY, **Maciejewski MF**, Rubakhin SS, Romanova EV, Bell AM, Sweedler JV. Single cell chemistry of the three-spined stickleback pituitary: implications in parenting behaviors.
\ 

Matthews DG, **Maciejewski MF**, Wong GA, Lauder GV, Bolnick DI. Locomotor effects of a fibrosis-based immune response in stickleback fish. [Preprint Link](https://www.biorxiv.org/content/10.1101/2023.06.24.546342v2)
\ 

Behrens C, **Maciejewski MF**, Dalziel AC, Weir LK, Bell AM. A rapid divergence in reproductive behaviors accompanies the evolutionary loss of parental care.


\
\

For an up-to-date list of publications, see my [Google Scholar](https://scholar.google.com/citations?user=EJt3cOkAAAAJ&hl=en) page
